# Generated by Django 6.0.3 on 2026-05-17 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(help_text='Número único do pedido', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_picking', 'Em Picking'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=255)),
                ('sku', models.CharField(help_text='SKU único do produto', max_length=50, unique=True)),
                ('cor', models.CharField(blank=True, help_text='Cor do produto', max_length=100)),
                ('tamanho', models.CharField(blank=True, help_text='Tamanho do produto', max_length=50)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada')),
                ('ativo', models.BooleanField(default=True, help_text='Se o produto está ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corredor', models.CharField(help_text='Ex: A, B, C, D...', max_length=10)),
                ('secao', models.CharField(help_text='Ex: 01, 02, 03...', max_length=10)),
                ('nivel', models.CharField(help_text='Ex: 1A, 2B, 3C...', max_length=10)),
                ('descricao', models.CharField(blank=True, help_text='Descrição da localização', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
                'ordering': ['corredor', 'secao', 'nivel'],
                'unique_together': {('corredor', 'secao', 'nivel')},
            },
        ),
        migrations.CreateModel(
            name='Picking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('iniciado', 'Iniciado'), ('em_progresso', 'Em Progresso'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='iniciado', max_length=20)),
                ('inicio', models.DateTimeField(auto_now_add=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.IntegerField(default=0)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickings', to='picking.pedido')),
                ('usuario', models.ForeignKey(help_text='Operador responsável', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Picking',
                'verbose_name_plural': 'Pickings',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Quantidade necessária')),
                ('quantidade_coletada', models.IntegerField(default=0, help_text='Quantidade já coletada')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_picking', 'Em Picking'), ('confirmado', 'Confirmado'), ('falta', 'Em Falta'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('localizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='picking.localizacao')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='picking.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='picking.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'ordering': ['pedido', 'produto'],
            },
        ),
        migrations.CreateModel(
            name='Erro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sku_invalida', 'SKU Inválida'), ('quantidade_excessiva', 'Quantidade Excessiva'), ('produto_nao_encontrado', 'Produto Não Encontrado'), ('localizacao_errada', 'Localização Errada'), ('item_falta', 'Item em Falta'), ('dano', 'Produto Danificado'), ('outro', 'Outro')], help_text='Tipo do erro', max_length=50)),
                ('descricao', models.TextField(help_text='Descrição detalhada do erro')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('resolucao', models.TextField(blank=True, help_text='Como foi resolvido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='erros', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erros', to='picking.pedido')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='picking.produto')),
            ],
            options={
                'verbose_name': 'Erro',
                'verbose_name_plural': 'Erros',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='TentativaValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_informado', models.CharField(max_length=50)),
                ('resultado', models.CharField(choices=[('sucesso', 'Sucesso'), ('sku_invalida', 'SKU Inválida'), ('quantidade_atingida', 'Quantidade Atingida'), ('outro', 'Outro')], max_length=50)),
                ('mensagem', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='picking.itempedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_validacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tentativa de Validação',
                'verbose_name_plural': 'Tentativas de Validação',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, help_text='Quantidade disponível')),
                ('quantidade_reservada', models.IntegerField(default=0, help_text='Quantidade reservada em pedidos')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='picking.localizacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='picking.produto')),
            ],
            options={
                'verbose_name': 'Produto por Localização',
                'verbose_name_plural': 'Produtos por Localização',
                'unique_together': {('produto', 'localizacao')},
            },
        ),
    ]
